### ISSUE TITLE
ShowBreadcrumb does not output trace in release build / nuget install

### ISSUE THREAD

**Issue by willdean** [GregFinzer/Compare-Net-Objects#67]
We would like to use ShowBreadcrumb to diagnose some performance problems probably caused by excessively deep recursion into our objects (we have previously used it successfully like this).

However, there's a minor stumbling-block: `BaseComparer.AddBreadCrumb` contains the following code:

```
        if (config.ShowBreadcrumb)
                Debug.WriteLine(sb.ToString());
```

The problem is that a release build (and hence the Nuget package) compiles Debug.WriteLine away to nothing, so this doesn't work unless you pull the source and build your own Debug build (which is what we did last time we needed this feature).

Is there another way to use ShowBreadcrumb in a release/nuget install, or should this line actually say `Trace.WriteLine(sb.ToString)` so that the call stays active in the release build?

If this is a bug, would you like a (trivial) PR?

**Comment by GregFinzer** [comment]
Will,

I am very busy but I will definitely change this in the next release.   I mainly use the ShowBreadCrumb myself for debugging large object graphs when there are comparison problems.

Thanks,
Greg

**Comment by willdean** [comment]
Thanks Greg - unfortunately because the library is a PCL, you can't merely use `Trace.WriteLine`, which makes it slightly more of a pain to sort out than it would otherwise be.

**Comment by GregFinzer** [comment]
Done.  Nuget package 4.01 is available now

**Comment by willdean** [comment]
Thanks very much for looking at this, but it doesn't actually seem to work in the new Nuget release.

The source changes look fine, but don't seem to have made it through to the binaries - there's no additional output and the decompiled code doesn't have the `Trace` call:

```
    protected string AddBreadCrumb(ComparisonConfig config, string existing, string name, string extra, string index)
    {
      if (config == null)
        throw new ArgumentNullException(nameof (config));
      bool flag1 = !string.IsNullOrEmpty(index);
      if (name == null)
        throw new ArgumentNullException(nameof (name));
      bool flag2 = name.Length > 0;
      StringBuilder stringBuilder = new StringBuilder();
      stringBuilder.Append(existing);
      if (flag2)
      {
        stringBuilder.AppendFormat(".");
        stringBuilder.Append(name);
      }
      stringBuilder.Append(extra);
      if (flag1)
      {
        int result = -1;
        stringBuilder.AppendFormat(int.TryParse(index, out result) ? "[{0}]" : "[\"{0}\"]", (object) index);
      }
      int num = config.ShowBreadcrumb ? 1 : 0;
      return stringBuilder.ToString();
    }
```

I am wondering if there was a build problem - the assembly version is still 3.9 and might have been built as a debug version:

![image](https://user-images.githubusercontent.com/1306085/33930689-a36d43f2-dfe5-11e7-98ae-b080c77e2af7.png)

**Comment by GregFinzer** [comment]
I will look at in a few days.  The semi-automatic build process that I have for for Compare .NET Objects is not as advanced as my other libraries.  There could be a problem.

**Comment by GregFinzer** [comment]
Rebuilt.  Try it now.

**Comment by willdean** [comment]
Thanks Greg - unfortunately it still doesn't work, on a .NET 4.6 project.

If I build the source myself in VS (release build), then I get a `Trace.WriteLine()` in the right place in BaseComparer.   But in the Nuget version (which is dated 21 Dec, so it's definitely the latest) I don't.

Sorry not to have better news :-(

**Comment by GregFinzer** [comment]
@willdean Honestly I have no idea why.

**Comment by willdean** [comment]
Nor do I and I spent some time messing around in VS to see if I could see why, but I don't really know how you build it all - do you run msbuild by hand from the command line?

**Comment by willdean** [comment]
@GregFinzer I will help with this, but I need to understand how you build the nuget package.  It doesn't seem that everything you use to do that is in Github (e.g. no nuspec), and I can't repro the problem if I just build the DLL in VS.

**Comment by GregFinzer** [comment]
@willdean Thanks.  Can you tell if the output is maybe a debug build instead of a release build?  I will look at my build tool over the weekend.  It is a custom application that uses MSBuild on the console.  I will get you the parameters that it is using.

**Comment by GregFinzer** [comment]
Will,

I looked at the code for the build tool and also looked at the log, and it is doing a release build for each version of the .NET Framework:  Example:
Shell C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe Compare-NET-Objects.csproj /t:Rebuild /p:Configuration=Release;TargetFrameworkVersion=v4.5.2 /p:DefineConstants="NET40;NET45;NET452"

Attached is the full log.
[CompareNetObjects4_4BuildLog.txt](https://github.com/GregFinzer/Compare-Net-Objects/files/1754620/CompareNetObjects4_4BuildLog.txt)

**Comment by willdean** [comment]
@GregFinzer Sorry for the terribly long delay on this - it became an issue for me again tonight, so I took another look and have finally got to the bottom of it - though I can't give you a PR because the problem appears to be in the build script which is not in the repo.

The issue is that the `/p:DefineConstants="NET40;NET45;NET452"` option on the command line *replaces* the constants  defined in the csproj file.  This loses, crucially, the TRACE constant - without which the `Trace.WriteLine` in `AddBreadCrumb` is removed at compile time.  It's hard to spot this, because if you look in the project settings in VS (or in the csproj file), the TRACE constant *is* set - it's only when msbuild is invoked with that command-line option that it gets removed.

So if you can change your build script to say `/p:DefineConstants="NET40;NET45;NET452;TRACE"` (and the equivalent for all the other platforms I guess) then we should be laughing. 

Thanks,

Will

**Comment by GregFinzer** [comment]
@willdean Good information!  Thanks so much. It will be a while until I can take a look at this.

**Comment by GregFinzer** [comment]
Fixed:  
https://github.com/GregFinzer/Compare-Net-Objects/releases/tag/4.54.0
https://www.nuget.org/packages/CompareNETObjects/4.54.0
